# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 869c414ceb6dd944145364017d35e581438c87e8ae330c61717dcfd5899671b02270368facedf1567eb19c10dce9cbdc8458f274d120c35e13dee53a99db16a1

test:
  secret_key_base: d3147023d772f99a98f549d582b5bf95244a2e05fd4d81138a2030e2fd330baa8066677b2144d6c41c201d19a1b9b47871d1a7a8dd1ba7e76e8e8d1d8ccab33e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
